# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-create_date', '-create_time']},
        ),
        migrations.AlterField(
            model_name='item',
            name='is_error',
            field=models.IntegerField(verbose_name='服务错误标志位'),
        ),
    ]
