# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20170327_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='record_time',
            new_name='record_date',
        ),
    ]
