# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20170328_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=300, verbose_name='用例名称')),
                ('case_time', models.DateTimeField(verbose_name='上传时间')),
            ],
            options={
                'ordering': ['-case_name'],
            },
        ),
    ]
