# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=300, verbose_name='模块名称')),
                ('item_name', models.CharField(max_length=300, verbose_name='条目名称')),
                ('error_type_flag', models.IntegerField(verbose_name='错误类型')),
                ('record_date', models.DateField(verbose_name='记录时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Item')),
            ],
            options={
                'ordering': ['-item'],
            },
        ),
    ]
